- name: Install dependencies for setting up apt sources
  become: true
  ansible.builtin.apt:
    name:
      - curl
      - gnupg
      - lsb-release
      - locales
      - software-properties-common
    update_cache: true

- name: Generate and set locale
  become: true
  ansible.builtin.locale_gen:
    name: en_US.UTF-8
    state: present

- name: Update locale
  become: true
  ansible.builtin.command: update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
  changed_when: false

- name: Add universe repository
  become: true
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    state: present
  loop:
    - "deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} universe"
    - "deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }}-updates universe"

- name: Get latest ROS 2 apt source version
  ansible.builtin.uri:
    url: https://api.github.com/repos/ros-infrastructure/ros-apt-source/releases/latest
    method: GET
    return_content: true
  register: ros_apt_source_release

- name: Extract version tag
  ansible.builtin.set_fact:
    ros_apt_source_version: "{{ ros_apt_source_release.json.tag_name }}"

- name: Get Ubuntu codename
  ansible.builtin.shell: . /etc/os-release && echo $VERSION_CODENAME
  register: ubuntu_codename
  changed_when: false

- name: Download ROS 2 apt source package
  ansible.builtin.get_url:
    url: "https://github.com/ros-infrastructure/ros-apt-source/releases/download/{{ ros_apt_source_version }}/ros2-apt-source_{{ ros_apt_source_version }}.{{ ubuntu_codename.stdout }}_all.deb"
    dest: /tmp/ros2-apt-source.deb
    mode: '0644'

- name: Install ROS 2 apt source package
  become: true
  ansible.builtin.apt:
    deb: /tmp/ros2-apt-source.deb
    state: present
    update_cache: true

- name: Hold check of ros-{{ rosdistro + '-' + ros2_installation_type }}
  ansible.builtin.command: apt-mark showhold
  register: held_ros_packages
  changed_when: false

- name: Install ros-{{ rosdistro + '-' + ros2_installation_type }}
  become: true
  ansible.builtin.apt:
    name: ros-{{ rosdistro }}-{{ ros2_installation_type }}
    state: latest
    update_cache: true
  when: "'ros-' + rosdistro + '-' + ros2_installation_type not in held_ros_packages.stdout"
  register: install_result
  failed_when: false

- name: Display warning if ROS 2 package is held
  ansible.builtin.debug:
    msg: ROS package 'ros-{{ rosdistro + '-' + ros2_installation_type }}' is apt-mark hold. Skipping installation.
  when: not install_result.changed

- name: Install ROS 2 development tools
  become: true
  ansible.builtin.apt:
    name: ros-dev-tools
    state: latest
    update_cache: true

- name: Add PATH to .bashrc
  become: true
  ansible.builtin.lineinfile:
    dest: "{{ item }}"
    line: source /opt/ros/{{ rosdistro }}/setup.bash
    state: present
    create: true
    mode: 0644
  loop:
    - ~/.bashrc
    - /etc/skel/.bashrc
