---
galaxy_info:
  role_name: autosdv_python_deps
  author: AutoSDV Team
  description: Python dependencies for AutoSDV vehicle interface
  license: Apache License 2.0
  min_ansible_version: "2.10"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy

dependencies: []