- name: Set up source development environments for Autoware Universe
  hosts: localhost
  connection: local
  vars_prompt:
    - name: prompt_download_artifacts
      prompt: |-
        [Warning] Should the ONNX model files and other artifacts be downloaded alongside setting up the development environment.
        Download artifacts? [y/N]
      private: false
    - name: install_devel
      prompt: |-
        [Warning] Do you want to install recommended development tools for Autoware? [y/N]
      private: false
      default: y
  pre_tasks:
    - name: Verify OS
      ansible.builtin.fail:
        msg: Only Ubuntu 22.04 is supported for this branch. Please refer to https://autowarefoundation.github.io/autoware-documentation/main/installation/autoware/source-installation/.
      when: ansible_distribution_version != '22.04'

    - name: Print args
      ansible.builtin.debug:
        msg:
          - rosdistro: "{{ rosdistro }}"
          - rmw_implementation: "{{ rmw_implementation }}"

  roles:
    # Autoware base dependencies
    - role: autoware.dev_env.ros2
    - role: autoware.dev_env.ros2_dev_tools
    - role: autoware.dev_env.rmw_implementation
    - role: autoware.dev_env.gdown
    - role: autoware.dev_env.build_tools

    # Autoware module dependencies
    - role: autoware.dev_env.geographiclib
    - role: autoware.dev_env.pacmod
      when: rosdistro != 'rolling'

    # Autoware devel dependencies
    - role: autoware.dev_env.dev_tools
      when: install_devel == 'y'

    # ONNX files and other artifacts
    - role: autoware.dev_env.artifacts
      when: prompt_download_artifacts == 'y'
