---
- name: Install U-Blox GPS udev rules
  become: true
  ansible.builtin.copy:
    src: 99-ublox-gps.rules
    dest: /etc/udev/rules.d/99-ublox-gps.rules
    mode: "0644"
    owner: root
    group: root
  register: udev_rules_installed

- name: Add user to dialout group
  become: true
  ansible.builtin.user:
    name: "{{ ansible_env.USER }}"
    groups: dialout
    append: yes
  register: user_added_to_dialout

- name: Reload udev rules
  become: true
  ansible.builtin.command:
    cmd: udevadm control --reload-rules
  when: udev_rules_installed.changed

- name: Trigger udev rules
  become: true
  ansible.builtin.command:
    cmd: udevadm trigger
  when: udev_rules_installed.changed

- name: Display information about group membership
  ansible.builtin.debug:
    msg: "User {{ ansible_env.USER }} has been added to dialout group. You may need to log out and log back in for group changes to take effect."
  when: user_added_to_dialout.changed
