<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>ndt_pose_estimator_launch</name>
  <version>0.1.0</version>
  <description>NDT pose estimator plugin for modular localization</description>
  <maintainer email="autosdv@todo.todo">AutoSDV</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>autosdv_localization_launch</exec_depend>
  <exec_depend>autoware_ndt_scan_matcher</exec_depend>
  <exec_depend>autoware_pose_initializer</exec_depend>
  <exec_depend>autoware_automatic_pose_initializer</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
